### ISSUE TITLE
Database on government funding recipients

### ISSUE THREAD

**Issue by daschug** [okfde/fragdenstaat_de#168]
HI,
I'd like to create a database of government funding recipients, so a searchable list of all companies and institution which got funds from the state or governmental institutions for projects or as support for their business. While the corona help funds might be less interesting (who knows?), I'd especially like to focus on how the funds for digitization have been spread. I'd assume, that there are just a few players getting a major share without necessity, but that would be subject of further data analysis.
Best regards, Ralf

**Comment by akuckartz** [comment]
@daschug How is this issue related to fragdenstaat_de ?

**Comment by daschug** [comment]
Well, to fill this database It will need a lot of (recurring) requests of freedom of information and a perhaps you would also see a public benefit if a database like this would be available in public?

**Comment by Unterstrichmoepunterstrich** [comment]
Hello @daschug 

I agree, this issue is related to FdS.
However, enquiries to municipal enterprises, such as contracts between several parties or about undertakings planned for the future, are seldom answered, as they are based on business secrets and therefore have a right of objection, which is usually exercised. Although this means that you have an extended database, it is unlikely that you will receive information unless the database is a public law institution (AöR).

**Comment by stefanw** [comment]
Closing as not about the software. Please use our [forum](https://forum.okfn.de/).

Please also be aware of existing government portals that list project funding like [Förderkatalog](https://foerderportal.bund.de/foekat/jsp/StartAction.do).
