### ISSUE TITLE
POST https://fragdenstaat.de/anfrage-stellen/ 400 (Ihre Formulareingabe enthielt Fehler)

### ISSUE THREAD

**Issue by johnjohndoe** [okfde/fragdenstaat_de#214]
I am trying to submit a request which I send before to another authority. Therefore, I copied/pasted the subject and the text body. Once I submit the request the page responds with the following errors:

> Ihre Formulareingabe enthielt Fehler. Bitte überprüfen Sie Ihre Eingabe und senden Sie das Formular noch einmal.

> POST https://fragdenstaat.de/anfrage-stellen/ 400

![image](https://user-images.githubusercontent.com/144518/116285491-6d8bb880-a78e-11eb-8595-b875eaace0d3.png)

I am using Brave on Ubuntu.

**Comment by stefanw** [comment]
Am I right to assume that you were making a request that uses text from one of our campaigns? We need people to make these requests through the campaign interface in order to also store meta data about the request context (e.g. put the request on a map).

The error message was missing for that campaign and there wasn't a fallback (see https://github.com/okfde/froide/commit/50f95bd55a6f9ae6530b93b37655c265be79e1e0).

**Comment by johnjohndoe** [comment]
That is correct. Thank you for the clarification.

How can I change the receiver of the request once I found out that the predefined receiver of the campaign is not correct?

**Comment by stefanw** [comment]
The campaign interface makes it possible afaik to choose a recipient now. However, not sure about already running requests. If you can‘t start the request to the right authority through the campaign interface, open a problem report on your existing request via the „Problem?“ button and we will figure it out.
